version: '3'
services:
  py:
    #build: .
    image: registry.hub.docker.com/vicervin/dbopt:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #command: sleep 1h
    command: python dbopt/smac_runQueries.py > /tmp/console
