apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  volumes:
    - name: dshm
      emptyDir:
      medium: Memory
  containers:
    - name: postgres-pod
      image: postgres:11
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 5432
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm